### ISSUE TITLE
PPU fast mode - Trials of Mana resolution issues

### ISSUE THREAD

**Issue by joepogo** [libretro/bsnes-libretro#39]
It seems when using the PPU fast mode on Bsnes libretro and games like trials of Mana/seiken densetsu 3 (possibly other games) the screens switch rapidly from clear text back to blurry graphics after text screens disappear. 

Does the PPU fast mode on bsnes have issues with switching resolutions from 240p to 480i? I tested this with SNES9x and this problem does not persist. 

Using the accurate ppu mode on bsnes seems to work but shouldn't it work correctly either way in theory? 

I've tried toggling numerous settings but nothing seems to work and it's pretty jarring to watch screens go hi-res  with text back to low res. 

The issue is apparent as soon as you start the game fighting the level 1 knight.

**Comment by joepogo** [comment]
To further clarify I've tested this game with the crt-geom shader on both emulators in retroarch. 

SNES9x - works 
Bsnes accurate PPU mode - works 
Bsnes fast PPU -  doesn't.

**Comment by carmiker** [comment]
In this case it's because the width changes, not the height. With the accurate PPU it is always outputting double resolution horizontally, and only adjusts vertical resolution when needed. With the fast PPU, everything is adjustable because it has to be, given that there are all these different mode7 scale levels. In summary, this is the expected behaviour, as the shader is reacting to what it is being fed. It's the price you pay for using hacks/enhancements.
